import pandas as pd

df_posting: pd.DataFrame = pd.read_csv("https://drive.usercontent.google.com/download?id=1vM5fVPrZVtBruD7LLZVVeHVAApqQgHCt&export=download&authuser=0&confirm=t&uuid=802d5b6c-b596-4398-a3c1-caf0be5f834f&at=ALBwUgklTDT44mmgIpzoju6Uky2r%3A1778995998426")
df_skills: pd.DataFrame = pd.read_csv("https://drive.google.com/uc?export=download&id=1ftdeNOEpnm4a-mR6jI53K6u_d__ov2XB")
df_salaries: pd.DataFrame = pd.read_csv("https://drive.google.com/uc?export=download&id=1mtwW1JImMOLuWrm4nx4CLb_ZOlo4vAQr")
df_job_skills: pd.DataFrame = pd.read_csv("https://drive.google.com/uc?export=download&id=14O385R-O1d3P1zqSKFkHotdLRuW39DT8")
df_job_industries: pd.DataFrame = pd.read_csv("https://drive.google.com/uc?export=download&id=1tJgLzRYT5jEZaS_Idxa3OpJso6gVybtr")
df_industries: pd.DataFrame = pd.read_csv("https://drive.google.com/uc?export=download&id=1F_jJyBI0IMvXN2yZ5GeNaQHMgi2GJJtZ")
df_employee_counts: pd.DataFrame = pd.read_csv("https://drive.google.com/uc?export=download&id=1yMKvKqgpSLO2fyddrAjliOospckkEUsl")
df_company_specialities: pd.DataFrame = pd.read_csv("https://drive.google.com/uc?export=download&id=1JYg9xauTVR6hf4uHJPklxqtiqdPhNC21")
df_company_industries: pd.DataFrame = pd.read_csv("https://drive.google.com/uc?export=download&id=1EeVRluUpy0-UyxFbrLptMYroZK8YM5_i")
df_companies: pd.DataFrame = pd.read_csv("https://drive.google.com/uc?export=download&id=1nTnBwtOibA3f9areJNXMPK7TH_lJ5i2P")
df_benefits: pd.DataFrame = pd.read_csv("https://drive.google.com/uc?export=download&id=17qOKff9mORXwLAKrLGVBTDsxl_YgqskU")

# df_posting: pd.DataFrame = pd.read_csv("data/job_posting.csv")
# df_skills: pd.DataFrame = pd.read_csv("data/skills.csv")
# df_salaries: pd.DataFrame = pd.read_csv("data/salaries.csv")
# df_job_skills: pd.DataFrame = pd.read_csv("data/job_skills.csv")
# df_job_industries: pd.DataFrame = pd.read_csv("data/job_industries.csv")
# df_industries: pd.DataFrame = pd.read_csv("data/industries.csv")
# df_employee_counts: pd.DataFrame = pd.read_csv("data/employee_counts.csv")
# df_company_specialities: pd.DataFrame = pd.read_csv("data/company_specialities.csv")
# df_company_industries: pd.DataFrame = pd.read_csv("data/company_industries.csv")
# df_companies: pd.DataFrame = pd.read_csv("data/companies.csv")
# df_benefits: pd.DataFrame = pd.read_csv("data/benefits.csv")